-- Run this in Supabase SQL Editor

create table if not exists page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx on page_views (created_at);
create index if not exists page_views_path_idx on page_views (path);

alter table page_views enable row level security;

-- Anyone visiting the public site can log a view
create policy "Allow public insert on page_views"
  on page_views
  for insert
  to anon
  with check (true);

-- Only logged-in users (admin) can read the analytics data
create policy "Allow authenticated read on page_views"
  on page_views
  for select
  to authenticated
  using (true);
